# Site settings
title: Hoteles y Restaurantes de la ciudad de Ayacucho 
email: danny@mapbox.com
description: > # this means to ignore newlines until "baseurl:"
  <h2>Ayacucho</h2>
  Ayacucho es conocida como la ciudad de 33 iglesias, en esta pagina podra encontrar informacion acerca de los restaurantes 
  y hoteles de la ciudad.

baseurl: /proyecto # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
highlighter: pygments
encoding: utf-8
# Build settings
markdown: kramdown
